---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ruby_for_busser: true
  require_chef_for_busser: false
  ansible_sudo: yes
  ignore_paths_from_root:
    - .git
    - .idea

# HACK: workaround for problem with net/ssh/connection/channel.rb:541:in `do_open_failed': open failed (1) (Net::SSH::ChannelOpenFailed): https://github.com/test-kitchen/test-kitchen/issues/1035
transport:
  max_ssh_sessions: 5

platforms:
  - name: ubuntu-14.04

suites:
  - name: py27
    run_list:
    attributes:
  - name: py36
    run_list:
    attributes:            
