---
rvm:
- 2.3

before_script:
- source <(curl -sL https://raw.githubusercontent.com/zuazo/kitchen-in-travis/0.5.0/scripts/start_docker.sh)
- gem install rake kitchen-ansible kitchen-docker

script:
- kitchen test py27
- kitchen test py36

