---
- include_vars: "{{item}}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- include: Debian.yml
  when: ansible_os_family == "Debian"
